# Generated by Django 5.2.7 on 2026-02-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0002_emailverification_passwordresettoken_supplierorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={},
        ),
    ]
