# Generated by Django 5.2.7 on 2026-02-17 02:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0003_alter_passwordresettoken_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplier_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auto_app.supplierorder'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_app.product'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='status',
            field=models.CharField(default='created', max_length=50),
        ),
    ]
